FROM python:3.10-slim
# FROM nvidia/cuda:12.3.0-runtime-ubuntu22.04
# RUN apt-get -y update && apt-get install -y software-properties-common && add-apt-repository universe
# RUN apt-get -y install python3.10
# RUN apt-get -y install python3-pip
RUN pip install --upgrade pip
COPY requirements.worker.txt .
RUN pip install -r requirements.worker.txt
WORKDIR /app
COPY . /app
RUN python3.10 -m spacy download en_core_web_sm
CMD ["python3", "app.py"]
